### ISSUE TITLE
Adopt a schedule of EEW meetings

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#166]
Proposed:

| Structure | Cadence | Format & Purpose |
|-|-|-|
| 1:1 with manager | Weekly or biweekly (set up a standing time) | Open discussion call, should cover: are you learning and growing, how are you doing, what is coming up for you as you do this work |
| Sprint planning meeting (Tuesdays) | Weekly | Set a milestone goal for the next week & get a sense of who is doing what |
| Onboarding | Once? Set of meetings? | Get situated with EEW goals and your role within the team |
| Social | Weekly (set up a standing time) | A place to decompress, hang out, no agenda, it's ok to talk about non EDGI things, *this is still paid time; building our community & being human together is important*
| Scrum | Daily but optional (set a time) | Each person gets 1 minute: what did you do since last mtg, what are you doing until next, any concerns or blockers |

Based on https://github.com/edgi-govdata-archiving/EEW_Planning/issues/90 meetings

┆Issue is synchronized with this [Trello card](https://trello.com/c/6Qhr7bJt)

**Comment by Frijol** [comment]
I was thinking about how to do morning scrum when we're in different time zones and decided trying an automated asynchronous approach might be helpful. I made a scrum bot in a new channel called #eew_daily_scrum. Curious to hear what you all think of this vs trying to get face to face scrum time on a daily basis

**Comment by lourdesvera** [comment]
| Structure | Cadence | Format & Purpose |
|-|-|-|
| 1:1 with manager | Weekly (set up a standing time with them) | Open discussion call, should cover: are you learning and growing, how are you doing, what is coming up for you as you do this work |
| Sprint planning meeting (Tuesdays) | Weekly | Set a milestone goal for the next week & get a sense of who is doing what |
| Onboarding | First-day orientation meeting then demos thereafter | Get situated with EEW goals and your role within the team |
| Social | Weekly Thursdays 3:30-4:30 after EEW meeting | A place to decompress, hang out, no agenda, it's ok to talk about non EDGI things, *this is still paid time; building our community & being human together is important*
| Scrum | Daily but optional in the EEW_Daily_Scrum channel| Each person gets 1 minute: what did you do since last mtg, what are you doing until next, any concerns or blockers |

**Comment by Frijol** [comment]
Sounds great. I put the social on the EDGI calendar. So the only thing to resolve then is making sure managers set up weekly 1:1s with all the interns they manage! @ericnost @lourdesvera @saraannwylie

**Comment by saraannwylie** [comment]
I'll work with Megan on this next week to figure out a time that works for her.

**Comment by Frijol** [comment]
pinging on this @lourdesvera @ericnost I don't think we listed the existence of these in any of the onboarding docs so making sure you see it & remember to set it up

**Comment by ericnost** [comment]
@Frijol Yes, I think Steve and I have set up Tuesdays 12:30 ET before the database meeting as a weekly meeting with Maalvika!

**Comment by lourdesvera** [comment]
@ericnost @Frijol @saraannwylie let's I'm going to add these to the EEW planning calendar, schedule to the onboarding document, and then let's close this issue?
