### ISSUE TITLE
Create questions for Storytelling Mural Board

### ISSUE THREAD

**Issue by crgreenleaf** [edgi-govdata-archiving/EEW_Planning#184]
- Choose a place (city/town/neighborhood) that matters to you like your hometown, current home, vacation area, place you've traveled to (Choose 1 and post a photo of it)
- List 3 three topographical landmarks that you remember or stick out about that place
- Do you have a memory you associate with those landmarks? (Write a blurb about a particular memory from this place in a sticky note)
- Has this place changed over the years? If yes, how so? If no, why do you think that is? (Sticky note)
- What were your schools like? (Photo/blurb)
- Did you perceive the places you grew up/live currently as racially or economically diverse? What did/do you notice about it?
- Were there any prominent facilities in any of these places that that people got/get angry or have arguments about? How does that make you feel? Were/are you angry? (In my town there was a nuclear power plant that people in my town were trying to shut down for years but many people's parent's worked there so there became an ideological divide between kids who lived in Vernon versus Brattleboro).
- Have people in your area ever had health problems that they attributed to lived environment?
- Have you ever been worried that your own health might be affected by something out of your control like external pollution, etc.?
- Do you have a first memory of learning about pollution, climate change, deforestation, environmental problems, etc? (Blurb)
- What do you think is the main problem?
- What is the first time you felt empowered to fight these forces?
- What gives you hope? (Photo)
┆Issue is synchronized with this [Trello card](https://trello.com/c/hfDje4Xr)

**Comment by crgreenleaf** [comment]
- Choose a place (city/town/neighborhood) that matters to you like your hometown, current home, vacation area, place you've traveled to (Choose 1 and post a photo of it) 
- List 3 three topographical landmarks that you remember or stick out about that place
- Do you have a memory you associate with those landmarks? (Write a blurb about a particular memory from this place in a sticky note)
- Has this place changed over the years? If yes, how so? If no, why do you think that is? (Sticky note)
- What were your schools like? (Photo/blurb)
- Did you perceive the places you grew up/live currently as racially or economically diverse? What did/do you notice about it? 
- Were there any prominent facilities in any of these places that that people got/get angry or have arguments about? How does that make you feel? Were/are you angry? (In my town there was a nuclear power plant that people in my town were trying to shut down for years but many people's parent's worked there so there became an ideological divide between kids who lived in Vernon versus Brattleboro). 
- Have people in your area ever had health problems that they attributed to lived environment?
-  Have you ever been worried that your own health might be affected by something out of your control like external pollution, etc.?
- Do you have a first memory of learning about pollution, climate change, deforestation, environmental problems, etc? (Blurb)
- What do you think is the main problem? 
- What is the first time you felt empowered to fight these forces?
- What gives you hope? (Photo)

**Comment by crgreenleaf** [comment]
@lesliealanis @calderEDJ Let me know if you have thoughts on these? I'm unsure how many of these would fit into an hour and I think we will definitely need to have a practice session to see

**Comment by lesliealanis** [comment]
Hi! @crgreenleaf @calderEDJ 
I added some to these questions:

- Choose a place (city/town/neighborhood) that matters to you like your hometown, current home, vacation area, place you've traveled to, **place of your favorite childhood memories** (Choose 1 and post a photo of it)

- What were your schools like?  **Do you feel they encouraged a learning environment? Do you feel that these schools had the resources to allow you to thrive after education? Why or why not?** (Photo/blurb)

I added these questions:

- Have people in your area ever had health problems that they attributed to their **work** environment?

- What, if anything discourages you, and what do you do to challenge that? (photo) 

- Have you personally been affected by an environmental issue? If so how? If not, why do you think that is?

- Have things gone generally better or worse in the place/places where you grew up? How so? (_Might be kind of redundant since we already have the fourth question._)

These were my favorite questions:

- Have you ever been worried that your own health might be affected by something out of your control like external pollution, etc.?

- Do you have a first memory of learning about pollution, climate change, deforestation, environmental problems, etc? (Blurb)

- What is the first time you felt empowered to fight these forces?

- Choose a place (city/town/neighborhood) that matters to you like your hometown, current home, vacation area, place you've traveled to, place of your favorite childhood memories (Choose 1 and post a photo of it)

- What gives you hope? (Photo)

I love the idea of us sharing first, I think it encourages people to tell their stories:

- Were there any prominent facilities in any of these places with which people got/get angry or had/have arguments about? How does that make you feel? Were/are you angry? (In my town there was a nuclear power plant that people in my town were trying to shut down for years but many people's parent's worked there so there became an ideological divide between kids who lived in Vernon versus Brattleboro).

**Comment by crgreenleaf** [comment]
Another idea is adding a module where we look at the EPA EJ screen tool in relation to where we are running the notebooks and see what people's impressions are with that.

**Comment by lesliealanis** [comment]
Great idea, that way tits related to the notebooks.

**Comment by lesliealanis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create questions for Storytelling Mural Board #184](https://trello.com/c/e7Lcru0k/79-create-questions-for-storytelling-mural-board-184)

**Comment by lourdesvera** [comment]
> <@US9DN9T0D> is this issue finished? or it's been integrated into the storytelling primer? I'm trying to see what we need to do to close it.<https://github.com/edgi-govdata-archiving/EEW_Planning/issues/184>
<sub>[View in Slack](https://edgi.slack.com/archives/C015DK0LKPS/p1593534108002100)</sub>

**Comment by lourdesvera** [comment]
Closing because it's moved on to the primer
