### ISSUE TITLE
Graphic Design

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#29]
┆Issue is synchronized with this [Trello card](https://trello.com/c/u3OZcbDq)

**Comment by Frijol** [comment]
What specifically needs graphic design? Issue needs more detail in order for someone to claim and/or resolve it

**Comment by lourdesvera** [comment]
We need to change the aesthetic on the website and choose the logo. Is there another issue for this?

**Comment by crgreenleaf** [comment]
@lourdesvera @Frijol At the moment in graphic works we have a sample reports for Louisiana 2nd c district, the congressional report card, and outreach materials. Because all of these are in Canva I think we should make separate issues for each and add the open editing links and make permission open to the whole team. I'll add these as issues. 

It might be worth discussing getting Canva premium for the summer if we're going to be using it. Could also be really great to offer this as a tool for the data visualization track.
