### ISSUE TITLE
EEW Report Louisiana 2nd Congressional District

### ISSUE THREAD

**Issue by crgreenleaf** [edgi-govdata-archiving/EEW_Planning#83]
┆Issue is synchronized with this [Trello card](https://trello.com/c/pC6kwlaA)

**Comment by crgreenleaf** [comment]
https://www.canva.com/design/DAD8DeOt_ds/G8Gl4K9XdLUlBrGO_-UhOw/edit

**Comment by calderEDJ** [comment]
https://www.canva.com/design/DAD8DeOt_ds/7JttmhvLBLUGzhQbK8HMXA/view?utm_content=DAD8DeOt_ds&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton
I'm at a bit of a stand still on this. All the data from the notebooks used at the Stonybrook event are in the report, and I've gotten some info in the Research and Conceptualization track regarding congressional representatives and their campaign donors, but I'm not sure where to go next. @ericnost @Frijol any ideas for the data viz section or edits on the report-making section? @saraannwylie @lourdesvera do either of you have an notes / suggestions on what to add to research and contextualization? I have a line of communication with Sharon Lerner of The Intercept; she would likely have some resources/info specific to this district.

**Comment by Frijol** [comment]
What's the ultimate goal/audience of this report? This is a sample report for what we're intending to make in general?

**Comment by ericnost** [comment]
Hi @calderEDJ  - This looks great!!! Some thoughts - do we need a separate data viz section? Seems to me the data viz is happening in the "report-making" section itself. 

Maybe we could figure out some sort of map showing total number of violations over time? What variable of interest do you think, based on your research, would be best to map? I can help do that.

In general, it seems a little weird to have separate "research and context", "data viz" and "storytelling" sections. To me, those 4 parts of the report-making model are just that - components that combine to provide the information in the report rather than structuring it. What if the report was structured around questions/answers?:

- What does environmental crime look like in *INSERT DISTRICT NAME HERE*? (# of violations, lack of enforcement, etc., relevant stories in a sidebar)
- What facilities are in violation? (map, stories about specific facilities)
- Who is letting this happen and why? (call out Rep and Senators, relevant stories in sidebars)
- Who is affected, what do they think, what are they doing, etc.? (report on community organizing?)

**Comment by ericnost** [comment]
(I might be misunderstanding something about the nature of the different tracks, but it seems like it would be valuable if they were synthesized for the report rather than separate.)

**Comment by saraannwylie** [comment]
It seems pretty difficult to collectively edit canva...Thoughts on this? Can you export a pdf that we can mark up? But in the long term should we find something that's easier for multiple people to work on? What do you think @crgreenleaf  @Frijol @calderEDJ? 

I agree with Eric's big picture comments. My thoughts for this is that it's an example of what a congressional report could look like, so I think we remove the mention of the tracks and probably the EWW diagram. Then I suggest moving up the information on who are the representatives for this district to before the findings. 

The information about what EWW is and why enforcement is important could probably be merged into 1 page. 

We should aim for something that is overall in the 5-7 pages range, because people won't read much after that.

I don't think we should include their rankings from other organizations unless we are clearly critiquing them because it's potentially confusing.

We need to work on the legends and axis to make sure that the charts are clearly understandable.

Also we need to rerun this report with the correct date range @ericnost could you help @calderEDJ with that?

**Comment by saraannwylie** [comment]
@calderEDJ can we find time tomorrow to work on a revision of this report? How about 11?

**Comment by mraisle** [comment]
@calderEDJ is there a place where the text is? Only link I see here is canva

**Comment by lourdesvera** [comment]
We decided to make this into a sample report to post on our blog and give to potential partner organizations.

It might be a good idea to send this report to communities in Louisiana.

**Comment by saraannwylie** [comment]
I can send this to Healthy Gulf in Lousiana @lourdesvera and @calderEDJ ? I'd like to get it ready for that. @calderEDJ could you put this in a draft or comment-able mode in Canva so it's easier to share feedback?

**Comment by saraannwylie** [comment]
@calderEDJ @crgreenleaf can we build an EDGI team on Canva so we can co-edit documents?

**Comment by saraannwylie** [comment]
Notes:

Text: "This willful, calculated harm is especially insidious because it represents an attitude of racial 
superiority that cannot be tolerated." Not sure we can prove "willful and calculated" also "attitude of racial superiority that cannot be tolerated" seems awkward better to name racism or white supremacy directly? Suggest revise to "the failure to abide by or enforcement environmental regulatory permits is a cause and consequence of environmental racism. We share these reports to reveal the vast gaps in environmental enforcement, the inadequacy of current data systems and to call regulators and industry to account."

**Comment by saraannwylie** [comment]
- Seems like the RCRA materials could be compressed into one page?

- Perhaps along with the Map of permitted facilities, there should be some key facts about this district? Louisiana 2nd district is a center for US chemical and fertilizer production as well as petroleum refining. Black communities have lead battles for Environmental Justice through out "cancer alley". Cancer rates a X's. Per capita income is X, Industrial revenue ---- some startling fact about profits generated here? 

- Should we add a report highlights section that pull out key facts "since Trump took office EPA has taken 0 enforcement actions" "the number of effluent violations have increased XXX" "there is less than 1% chance that a facility will be inspected by the EPA in year" 

- The definitions of the CWA violations should be explained in plain language.

- "Why have single event violations consistently declined while effluent violations have spiked? What additional context is needed here?" Single event violations have most likely declined because they are identified during inspections (i think). Suggest we change this line to focus on describing the spike in effluent violations (directly measured violations of what they are allowed to emit in their waste water).

- Should we look into some of the CWA enforcement cases that have happened under Trump in LA 2 and pull out some key facts? @mraisle I could see folks wanting to do that for all of these reports?

- Thinking on that what if the "template report" had links to resources that help you fill in each section, so the "use this url to look up representatives in this district" "use this link to look up their funding" "look up enforcement activities here" That way the template itself could be the guide for the research and contextualization track? @mraisle @calderEDJ ?

- Should we drop the district to district comparison? Or how do we move that forward? Could we come up with country wide averages to compare to?

- building on needing to highlight data gaps and problems should we add a page on Problems with this data, that includes general statements like "a lot of CAA data is based on estimates"

- If we are going to make the EJ point so strongly in the beginning I feel like we should include EJ screen statistic for each district?

- How/Where could health effects fit into this report? Or should we bracket that?

**Comment by lourdesvera** [comment]
Who else should we assign to this. @mraisle it seems your hands are full? @maalvikabhat? I can work on it too

**Comment by mraisle** [comment]
Hey @lourdesvera thanks for flagging! @calderEDJ and I met about this and then haven't spent time addressing Sara's comments. Addressing these would help us in thinking through the Sunrise report that we're a bit stuck on at the moment, also.

**Comment by mraisle** [comment]
Question for @lourdesvera  and @saraannwylie, after our conversation last week about our hesitation in including EJ metrics in the Sunrise notebook, do we have similar hesitations in expanding the EJ emphasis in a template report? Or should we pursue that?

**Comment by maalvikabhat** [comment]
I can work on this!

**Comment by maalvikabhat** [comment]
finished a EJ template!
