### ISSUE TITLE
Feedback on COVID-19 notebook

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/EEW_Planning#97]
Here on Github, in the comments below, please provide a review of the data analysis: https://colab.research.google.com/github/edgi-govdata-archiving/ECHO-COVID19/blob/master/ECHO-COVID19.ipynb

In this Google Doc, please mark up the context: https://docs.google.com/document/d/1cBeuUaS9ORW2ZlvZwiFB9EdpI7pR314RaWfQU9RNwro/edit?usp=sharing

┆Issue is synchronized with this [Trello card](https://trello.com/c/fbl6B9CC)

**Comment by saraannwylie** [comment]
Bug in Covid notebook, cell 15. I tried the COVID notebook for the first time. It ran great until Cell 15. Encountered an error. See screenshot, thought it might have been because I initially asked of May's data but tried it again with April as the month and encountered the same thing. Seemed to make all of the other cells break too up until 18/
<img width="930" alt="Screen Shot 2020-05-24 at 10 16 42 PM" src="https://user-images.githubusercontent.com/8268933/82772170-5d47bc80-9e0c-11ea-917c-2a2c7f682ff0.png">
<img width="881" alt="Screen Shot 2020-05-24 at 10 17 00 PM" src="https://user-images.githubusercontent.com/8268933/82772172-5f118000-9e0c-11ea-9c1f-85deb5b83b98.png">
<img width="983" alt="Screen Shot 2020-05-24 at 10 17 07 PM" src="https://user-images.githubusercontent.com/8268933/82772181-646eca80-9e0c-11ea-9dd2-de63292e6fdb.png">

**Comment by saraannwylie** [comment]
Second error encountered on cell 22, probably also related to loading info. from the EJ screening tool?
<img width="976" alt="Screen Shot 2020-05-24 at 10 22 50 PM" src="https://user-images.githubusercontent.com/8268933/82772477-3b9b0500-9e0d-11ea-9235-5768f9e68a8e.png">

**Comment by ericnost** [comment]
Thanks for flagging this Sara! Sorry you ran into this issue. The problem is that the code tries to find data from April 1 to April 31....but April 31 doesn't exist. So it'll work for May because May has 31 days. Anyway, a stupid bug, but should be easy to fix. In the meantime - everyone - run a month, like March or May, that has 31 days.... :(

**Comment by ericnost** [comment]
Hoping for feedback first from Cynthia Giles: https://github.com/edgi-govdata-archiving/EEW_Planning/issues/144

**Comment by Frijol** [comment]
Unblocked now?

**Comment by Frijol** [comment]
**Data science feedback:**

* Past Aprils – # of pollutants tested:
  * The very long history feels misleading & confusing (at least, without a lot more context). What if we confine it to the past 15 years? Would lean towards standardizing a history length for all of the data here
  *  I'm confused about using the metric "number of pollutants tested". Should this be "number of facilities?"
  * Would still be useful to get a bit more context on why the number trends up. Is this because it is an absolute number? New legislation? Both/other?
* PM/SO2 map: is it really just Maryland right now?
* Median percent minority: more effective as a pie chart? Right now the axes feel misleading (CAA and CWA)
* Median percent exceedance *says* median but the code calls `.mean()`

**Graphs feedback:**
Got inspired by datavis conversation, so here is a PR with a bunch of graph prettification! https://github.com/edgi-govdata-archiving/ECHO-COVID19/pull/23

**Comment by ericnost** [comment]
Thank you!!!! This itself is helpful, but I'll also look at the prettification.

>What if we confine it to the past 15 years? Would lean towards standardizing a history length for all of the data here

Yes, we need to cut back to 2001+ (or later) because of data quality issues #96 

>I'm confused about using the metric "number of pollutants tested". Should this be "number of facilities?"

Ok - will clarify "number of pollutants tested." Pollutants and facilities are two related, but distinct metrics here. Each facility can emit many different kinds of pollutants. They are permitted for and can be inspected for, violated, and receive enforcement penalties for more than one pollutant. Let's say Facility X emits 10 different things, from PM to SO2, lead, NOx, and more. Let's say it emitted more PM and more SO2 than its permit allows. We can either aggregate that information to say Facility X was in violation, or we can say there were 2 pollutants whose permits were exceeded. This results in different numbers. It is easier to calculate # of pollutants rather than # of facilities because we don't have to rollup the data (in most tables, each row/record refers to a single pollutant).

> Would still be useful to get a bit more context on why the number trends up. Is this because it is an absolute number? New legislation? Both/other?

Not sure what specific number you're thinking about here, but yes....context is good. We have a whole track for that! In addition, our meeting with Giles helped fill in some gaps...

> PM/SO2 map: is it really just Maryland right now?

Yea this was a little surprising to me too...

> Median percent minority: more effective as a pie chart? Right now the axes feel misleading (CAA and CWA)

This isn't a whole, it's a comparison of two percentages - the median % non-white in neighborhoods around ALL facilities, and the median % non-white in areas around the ones in violation (but of course that could be made more clear in the cell!!! Also I don't think this analysis is particularly incisive or fruitful, so am thinking of cutting). I'm not sure a pie chart is appropriate. I suppose it would be if we were interested in the % of all facilities in violation.

> Median percent exceedance says median but the code calls .mean()

Will look into! Certainly the chart titles need fixing.

**Comment by ericnost** [comment]
Thank you all so much for the feedback! I've incorporated into the latest version of the notebook. Still more work to be done, but am closing this issue for now.
